#!/usr/bin/with-contenv bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z 127.0.0.1 6379" \
        s6-setuidgid abc \
        	redis-server /config/redis.conf \
	            --bind 127.0.0.1 \
	            --port 6379 \
	            --pidfile /var/run/redis/redis.pid \
	            --always-show-logo no \
	            --dir /config/ \
	            --logfile /config/log/redis/redis.log
